export const BLOG_LOAD = 'BLOG_LOAD';
export const BLOG_LOAD_PART = 'BLOG_LOAD_PART'
export const BLOG_REQUEST = 'BLOG_REQUEST_OLD';
export const BLOG_SET_SUCCESS = 'BLOG_SET_SUCCESS_OLD';
export const BLOG_SET_ERROR = 'BLOG_SET_ERROR_OLD';
export const BLOG_SET_BLOGS_PER_PAGE = 'BLOG_SET_BLOGS_PER_PAGE';
export const BLOG_ADD_NEW = 'BLOG_ADD_NEW';
export const BLOG_SET_NUMBER_OF_PAGES = 'BLOG_SET_NUMBER_OF_PAGES';
