// define the actions allowed for reducers

export const EVENT_LOAD = 'EVENT_LOAD';
export const EVENT_LOAD_NEW = 'EVENT_LOAD_NEW';
export const EVENT_LOAD_OLD = 'EVENT_LOAD_OLD';
export const EVENT_LOAD_ALL = 'EVENT_LOAD_ALL';
export const EVENT_REQUEST_OLD = 'EVENT_REQUEST_OLD';
export const EVENT_SET_SUCCESS_OLD = 'EVENT_SET_SUCCESS_OLD';
export const EVENT_SET_ERROR_OLD = 'EVENT_SET_ERROR_OLD';
export const EVENT_REQUEST_NEW = 'EVENT_REQUEST_NEW';
export const EVENT_SET_SUCCESS_NEW = 'EVENT_SET_SUCCESS_NEW';
export const EVENT_SET_ERROR_NEW = 'EVENT_SET_ERROR_NEW';
export const EVENT_SET_EVENTS_PER_PAGE = 'EVENT_SET_EVENTS_PER_PAGE';
export const EVENT_ADD_NEW = 'EVENT_ADD_NEW';
export const EVENT_SET_NUMBER_OF_PAGES = 'EVENT_SET_NUMBER_OF_PAGES';

